### ISSUE TITLE
Configure code linter and formatter

### ISSUE THREAD

**Issue by jorgepiloto** [dnlzrgz/lazyfeed#5]
The project is lacking a tool for checking code style compliance. Knowing that [uv](https://docs.astral.sh/uv/) is used, what about going with [ruff](https://docs.astral.sh/ruff/)?

It is fast and collects various tools in a single one.

**Comment by jorgepiloto** [comment]
Back to this, what do you think about using also [pre-commit](https://pre-commit.com/) in the project, @dnlzrgz?

**Comment by dnlzrgz** [comment]
I just added `pre-commit` as a dev dependency with `ruff`'s linter and formatter.
